export const COMMUNITY_PROJECTS = [
  {
    id: "comm_proj_1",
    title: "Neural Code Reviewer & AST Analyzer",
    author: "Sophia Chen",
    authorUsername: "sophia_chen",
    authorAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBeN3wwzsfdCsKXyrCzamH7UFahjiEsN31mrLWG1dTJZdmoHpREvwUtzc4tXlXJvvZkiTKgnzU3pF6riYsq5MivKqaV7FOSlRalhtEQUPvFGe5L0xQ_iqOr2GQ3Pz5LLlZzjC1MBXQeW8LYjYcXWdLgoYanVyMrZj55berG-dYzEpklh-h-1msbQDrmiysCEy4htKIK8eDiNNtgrkzdHoQe5qGu7TPRJ6LijD9QoGtzJOWc9CIIRlbRoA",
    authorCollege: "Stanford University",
    language: "Python",
    category: "Machine Learning",
    tags: ["Python", "PyTorch", "AST", "Transformers", "Security"],
    stars: 148,
    likes: 284,
    badge: "Staff Pick",
    description: "Automated vulnerability scanner that parses Python and JavaScript AST syntax trees and detects memory leaks and SQL injections.",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80",
    time: "2h ago",
    filesCount: 14,
    commitsCount: 38
  },
  {
    id: "comm_proj_2",
    title: "KubeMesh Distributed Service Router",
    author: "Marcus Vance",
    authorUsername: "marcus_vance",
    authorAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCVz8ccn75U6PEveqo2Gd6S-MC5oDR_F1Z_uvXiVjuderm9XVEYN5WJOX1Swa3MoJSmhp8M2rAa0_HfLwyDKkVtOFAbeEuJDN6yKKM2Yw5k6YFlO9AkUBNtc2Gm0XGVmnGHO8I09aegiFn8M83GDJlEVF5A9rxXnl3j_nPB_U3Fu_gnFNOBu_2hhAguZ9NVm4Fh0qWAzZKiw3qka8qBhRs2gjvBglccXSwYl-qVmhv7QPq4KydK109dyQ",
    authorCollege: "MIT Tech",
    language: "Go",
    category: "Cloud & DevOps",
    tags: ["Go", "Kubernetes", "gRPC", "Docker", "Microservices"],
    stars: 96,
    likes: 192,
    badge: "Trending",
    description: "Lightweight zero-downtime service mesh controller for Kubernetes with Envoy sidecar auto-injection and Prometheus metrics.",
    image: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?auto=format&fit=crop&w=800&q=80",
    time: "5h ago",
    filesCount: 22,
    commitsCount: 54
  },
  {
    id: "comm_proj_3",
    title: "PacketGuard eBPF Kernel Firewall",
    author: "Elena Rostova",
    authorUsername: "elena_rostova",
    authorAvatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuDKKj6LVRj6za4b24SRqtjKKmW1JLRDJRyrWiHbxQZdg_ohwzJn-vZ29CTar7loXWqesAuTWKvPhwBtjqdW-zRp31xeHQcYqI90y6UaDDhD956vasWtK7NwGrrsR4mGYWfJoG6ar3kjZKjkF7aN89NBqeRMbxHhS5b9ARyvVau1ppYmfwQI4gFOLZVr5xsl62sMNPIPm9BYZmzG_zEow5ekx7pBHmu3CCJf3h0NGCyY9F9OSX_bbqKy-A",
    authorCollege: "Berkeley Engineering",
    language: "C",
    category: "Cybersecurity",
    tags: ["C", "Linux Kernel", "eBPF", "Cybersecurity", "Networking"],
    stars: 112,
    likes: 215,
    badge: "Verified Security",
    description: "Real-time network traffic inspector running inside the Linux kernel using extended Berkeley Packet Filters to mitigate L4/L7 DDoS attacks.",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
    time: "1d ago",
    filesCount: 9,
    commitsCount: 27
  },
  {
    id: "comm_proj_4",
    title: "OmniFlow Real-Time Audio DSP Synthesizer",
    author: "David Kim",
    authorUsername: "david_kim",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    authorCollege: "Carnegie Mellon University",
    language: "C++",
    category: "Systems",
    tags: ["C++", "DSP", "WebAudio", "Algorithms", "Performance"],
    stars: 84,
    likes: 167,
    badge: "Audio DSP",
    description: "Low-latency polyphonic digital signal processing engine with custom wavetable oscillators and real-time Fourier transform visualization.",
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=800&q=80",
    time: "2d ago",
    filesCount: 16,
    commitsCount: 42
  },
  {
    id: "comm_proj_5",
    title: "Next-Gen Bento UI Dashboard Canvas",
    author: "Aisha Patel",
    authorUsername: "aisha_patel",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80",
    authorCollege: "University of Washington",
    language: "TypeScript",
    category: "Web Dev",
    tags: ["React", "TypeScript", "Tailwind CSS", "Canvas", "UI/UX"],
    stars: 175,
    likes: 340,
    badge: "Popular UI",
    description: "Interactive draggable bento box dashboard with dark mode glassmorphism widgets and live websocket telemetry feed.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80",
    time: "3d ago",
    filesCount: 31,
    commitsCount: 89
  },
  {
    id: "comm_proj_6",
    title: "HyperGraph GPU Graph Analytics",
    author: "Carlos Mendez",
    authorUsername: "carlos_mendez",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    authorCollege: "Georgia Tech",
    language: "Rust",
    category: "Computer Science",
    tags: ["Rust", "CUDA", "Algorithms", "Parallel Computing"],
    stars: 120,
    likes: 228,
    badge: "High Perf",
    description: "Massively parallel PageRank and shortest-path graph traversal engine compiled to WebAssembly and native CUDA.",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80",
    time: "4d ago",
    filesCount: 18,
    commitsCount: 63
  }
];
